wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.18
    start_time: 1703109924.995133
    t:
      1:
      - 5
      - 50
      - 53
      - 55
      2:
      - 5
      - 50
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.18
      5: 0.13.11
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 100
dataset.name:
  desc: null
  value: bibtex
dataset.path:
  desc: null
  value: ../data/Bibtex/Bibtex_data.txt
debug:
  desc: null
  value: false
model._target_:
  desc: null
  value: contextualbandits.online.BootstrappedUCB
model.base_algorithm._target_:
  desc: null
  value: sklearn.linear_model.LogisticRegression
model.base_algorithm.solver:
  desc: null
  value: lbfgs
model.base_algorithm.warm_start:
  desc: null
  value: true
model.batch_sample_method:
  desc: null
  value: gamma
model.beta_prior:
  desc: null
  value: ${eval:'((5.0 / ${.nchoices}, 4), 2)'}
model.nchoices:
  desc: null
  value: 10
model.nsamples:
  desc: null
  value: 10
model.percentile:
  desc: null
  value: 50
model.random_state:
  desc: null
  value: ${..seed}
parser._target_:
  desc: null
  value: svmlight_parser.SvmlightParser
parser.filepath:
  desc: null
  value: ${..dataset.path}
parser.tail:
  desc: null
  value: ${..tail}
project:
  desc: null
  value: rl-bandits
seed:
  desc: null
  value: 1337
tail:
  desc: null
  value: null
